name: MobTalk
main: frostbyte.plugins.mobtalk.MobTalk
version: 0.1b
description: This plugin allows mobs to send chat messages upon various events.
author: _FrostByte_
website: http://dev.bukkit.org/bukkit-plugins/mobtalk/
permissions:
    mobtalk.mobtalk:
        description: Permission for the /mobtalk command
        default: op
    mobtalk.hear:
        description: Allows players to 'hear' mob speech in chat
        default: op
commands:
    mobtalk:
        aliases: mt
        description: version recites the version number, reload reloads the config
        permission: mobtalk.mobtalk
        